services:
  composer:
    # https://hub.docker.com/_/composer
    image: composer:2.1.12
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      COMPOSER_HOME: /.composer
    volumes:
      - ./:/app
      - ~/.composer:/.composer
    command: install

  test:
    # image: ideasonpurpose/phpunit-watch:dev
    image: ideasonpurpose/phpunit-watch:0.2.0
    volumes:
      - ./:/app
